import React from "react";
import KeyboardLetter from "../KeyboardLetter";
import KeyboardSpecial from "../KeyboardSpecial";
import Row from "../Row";
import "./Keyboard.css";

const Keyboard = props => (
  <div>
    <Row>
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="q"
        letter="q"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="w"
        letter="w"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="e"
        letter="e"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="r"
        letter="r"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="t"
        letter="t"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="y"
        letter="y"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="u"
        letter="u"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="i"
        letter="i"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="o"
        letter="o"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="p"
        letter="p"
      />
    </Row>
    <Row>
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="a"
        letter="a"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="s"
        letter="s"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="d"
        letter="d"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="f"
        letter="f"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="g"
        letter="g"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="h"
        letter="h"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="j"
        letter="j"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="k"
        letter="k"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="l"
        letter="l"
      />
    </Row>
    <Row>
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="z"
        letter="z"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="x"
        letter="x"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="c"
        letter="c"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="v"
        letter="v"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="b"
        letter="b"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="n"
        letter="n"
      />
      <KeyboardLetter
        onClick={props.handleBtnClick}
        data-value="m"
        letter="m"
      />
    </Row>
  </div>
);

export default Keyboard;
